#!/bin/sh

new_ext='.fpy'

#filename should be last element in list of options
FILE=${@: -1}

#Check its a file, if not we are linking not compiling:
if ! [[ -e "$FILE" ]];then
	gfortran -fPIC -shared $@ 
else
	x=${FILE##*/}
	y=${x%.*}
	output_file="$y"$new_ext
	
	gfortran -fdump-fortran-original -fPIC -shared $@ > "$output_file"
	if [[ $? -ne 0 ]];then
		rm "$output_file"
		exit 1
	fi
fi

exit 0
