name: Lint

on: [push, pull_request]
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: psf/black@stable
        with:
            options: "--check --verbose"