name: ci - gfortran8
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        fortran-compiler:  [gfortran-8]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    env:
      FC: ${{ matrix.fortran-compiler }}
      CC: gcc

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Setup compiler ${{ matrix.fortran-compiler }}
      run: |
        sudo apt-get update
        sudo apt-get install ${{ matrix.fortran-compiler }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        pip install -r requirements.txt

    - name: Test with tox
      run: tox -e py

