name: Run isort
on: [push, pull_request]
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'
          cache: 'pip'
      - uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326 #v1.1.1
        with:
            requirementsFiles: "requirements.txt"