# adapted from Numpy's linux-qemu.yml file
name: Linux Qemu tests

on: [push, pull_request]
permissions: {}

defaults:
  run:
    shell: bash

jobs:
  qemu:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        BUILD_PROP:
          - [
              "ppc64le",
              "powerpc64le-linux-gnu",
              "ppc64le/ubuntu:24.04",
              "linux/ppc64le",
          ]
          - [
              "s390x",
              "s390x-linux-gnu",
              "s390x/ubuntu:24.04",
              "linux/s390x",
          ]
          - [
              "riscv64",
              "riscv64-linux-gnu",
              "riscv64/ubuntu:24.04",
              "linux/riscv64",
          ]

    env:
      NAME: ${{ matrix.BUILD_PROP[0] }}
      TOOLCHAIN_NAME: ${{ matrix.BUILD_PROP[1] }}
      DOCKER_CONTAINER: ${{ matrix.BUILD_PROP[2] }}
      PLATFORM_NAME: ${{ matrix.BUILD_PROP[3] }}
      TERM: xterm-256color

    name: "${{ matrix.BUILD_PROP[0] }}"
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false

    - name: Initialize binfmt_misc for qemu-user-static
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes 

    - name: Cache docker container
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      id: container-cache
      with:
        path: ~/docker_${{ matrix.BUILD_PROP[1] }}.tar
        key: container-${{ matrix.BUILD_PROP[1] }}
        
    - name: Creates new container
      if: steps.container-cache.outputs.cache-hit != 'true'
      run: |
        docker run --name "${TOOLCHAIN_NAME}" --platform "${PLATFORM_NAME}" --interactive -v "$PWD":/gfort2py "${DOCKER_CONTAINER}" /bin/bash -c "
          apt-get update &&
          apt-get install -y cmake git python3 python-is-python3 python3-pip python3-dev automake libc6-dev linux-libc-dev gcc gfortran &&
          git config --global --add safe.directory /gfort2py
          "

        docker commit "${TOOLCHAIN_NAME}" "${TOOLCHAIN_NAME}"
        docker save -o "${HOME}/docker_${TOOLCHAIN_NAME}.tar" "${TOOLCHAIN_NAME}"

    - name: Load container from cache
      if: steps.container-cache.outputs.cache-hit == 'true'
      run: docker load -i "${HOME}/docker_${TOOLCHAIN_NAME}.tar"

    - name: Build and test
      run: |
        docker run -v "$PWD":/gfort2py --platform "${PLATFORM_NAME}" --ulimit core=0 "${TOOLCHAIN_NAME}" /bin/bash -c "
        cd /gfort2py && 
        export FC=$(which gfortran) && 
        export PIP_BREAK_SYSTEM_PACKAGES=1 &&
        python -m pip install --upgrade build wheel pytest &&
        python -m pip install --upgrade dist/gfort2py-*.whl && 
        python -m pytest -v"




